[program:home_energy_monitor]
command=/home/pi/Work/home-energy-monitor/venv/bin/python /home/pi/Work/home-energy-monitor/src/main.py
directory=/home/pi/Work/home-energy-monitor
user=pi

autostart=true
autorestart=true
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true

stdout_logfile=/home/pi/Work/home-energy-monitor/logs/app.out.log
stderr_logfile=/home/pi/Work/home-energy-monitor/logs/app.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=5
stderr_logfile_backups=5

environment=PYTHONUNBUFFERED=1